# Change these first
owner: fullprofile # Your GitHub organization or username, where this repository lives
repo: fullprofile-status-monitor # The name of this repository

sites:
  - name: Broker Xero Webhook
    url: https://xero-api.fullprofile.net/api/health


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.fullprofile.com.au
  # baseUrl: /your-repo-name
  logoUrl: https://uploads-ssl.webflow.com/5b553afd9b226816fd2ca19d/5b5540e9e5d2a80a9999e146_FP%20logo_white-p-500.png
  name: Fullprofile Status Monitor
  introTitle: "Fullprofile Status Monitor provides a quick look at our services and the uptime"
  navbar:
    - title: Status
      href: /
    - title: Knowledge Base
      href: https://fullprofile.atlassian.net/wiki/spaces/BRS/overview?homepageId=2303918367
    
i18n:
  footer: Grown by AgriDigital

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
