name: SSL/TLS Monitor 
on:
  workflow_dispatch

jobs:
  monitor:
    name: SSL/TLS Monitor
    runs-on: ubuntu-latest
    strategy:
      matrix:
        domain:
          - fullprofile.com.au
          - waypath.io
          - agridigital.io

    steps:
      - name: Monitor - ${{ matrix.domain }}
        uses: bluenovaio/action-tls-monitor@main
        with: 
          domain: ${{ matrix.domain }}
          expiration_days: 90
          approved_protocols: TLSv1.2,TLSv1.3
          alert_method: slack
          alert_token: ${{ secrets.NOTIFICATION_SLACK_WEBHOOK_URL }}

